import { Product, ProductCategory } from "@/types/product";

const defaultOffers = [
  {
    id: "offer-bank",
    title: "Bank Offer",
    description: "10% instant discount on HDFC Bank cards up to ₹1,500",
  },
  {
    id: "offer-emi",
    title: "No Cost EMI",
    description: "No cost EMI from ₹2,499/month",
  },
  {
    id: "offer-exchange",
    title: "Exchange Bonus",
    description: "Up to ₹4,000 exchange bonus on eligible devices",
  },
];

function buildGeneratedImageUrl(id: string) {
  return `/api/product-image/${id}`;
}

function buildReviewCopy(product: {
  name: string;
  brand: string;
  category: ProductCategory;
  rating: number;
  shortSpecs: string[];
}) {
  const leadSpec = product.shortSpecs[0] ?? "Balanced performance";
  const secondSpec = product.shortSpecs[1] ?? "Strong everyday usability";

  const categoryLine =
    product.category === "Mobiles"
      ? "Camera tuning and app smoothness both feel reliable."
      : product.category === "Laptops"
        ? "Thermals and multitasking stay under control during longer sessions."
        : product.category === "Tablets"
          ? "The screen and speakers make this a very usable entertainment device."
          : product.category === "Earbuds"
            ? "Call quality and audio separation both feel above average for the price."
            : "Health tracking and battery life feel practical in daily use.";

  return [
    {
      id: `${product.brand}-rv-1`,
      author: "Aarav S.",
      rating: Math.max(4, Number((product.rating - 0.1).toFixed(1))),
      comment: `${product.name} feels polished in daily use. ${leadSpec} stands out immediately.`,
      date: "2026-02-16",
    },
    {
      id: `${product.brand}-rv-2`,
      author: "Priya K.",
      rating: Math.max(4, Number((product.rating - 0.3).toFixed(1))),
      comment: `${secondSpec} helps this ${product.brand} option feel dependable for long-term use.`,
      date: "2026-03-01",
    },
    {
      id: `${product.brand}-rv-3`,
      author: "Nikhil R.",
      rating: Math.min(5, Number((product.rating + 0.1).toFixed(1))),
      comment: categoryLine,
      date: "2026-03-11",
    },
  ];
}

function toProduct(input: {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  releaseYear?: number;
  price: number;
  originalPrice: number;
  rating: number;
  ratingCount: number;
  image?: string;
  shortSpecs: string[];
  specs: Record<string, string>;
  ramGb: number;
  storageGb: number;
  bestChoice?: boolean;
  trending?: boolean;
}): Product {
  const image = buildGeneratedImageUrl(input.id);
  return {
    ...input,
    image,
    slug: input.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    gallery: [image, `${image}?view=alt-1`, `${image}?view=alt-2`],
    discountPercent: Math.round(
      ((input.originalPrice - input.price) / input.originalPrice) * 100,
    ),
    offers: defaultOffers,
    reviews: buildReviewCopy(input),
  };
}

export const fallbackProducts: Product[] = [
  toProduct({
    id: "m-1",
    name: "Samsung Galaxy M55 5G",
    brand: "Samsung",
    category: "Mobiles",
    releaseYear: 2024,
    price: 23999,
    originalPrice: 29999,
    rating: 4.4,
    ratingCount: 8421,
    image:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "256GB Storage", "5000mAh Battery", "50MP OIS"],
    specs: {
      Display: "6.7-inch FHD+ Super AMOLED, 120Hz",
      Processor: "Snapdragon 7 Gen 1",
      RAM: "8GB",
      Storage: "256GB",
      Camera: "50MP + 8MP + 2MP | 50MP Front",
      Battery: "5000mAh, 45W Fast Charging",
      OS: "Android 14",
    },
    ramGb: 8,
    storageGb: 256,
    bestChoice: true,
    trending: true,
  }),
  toProduct({
    id: "m-2",
    name: "iQOO Z9 Turbo",
    brand: "iQOO",
    category: "Mobiles",
    releaseYear: 2024,
    price: 19999,
    originalPrice: 24999,
    rating: 4.3,
    ratingCount: 5298,
    image:
      "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "128GB Storage", "6000mAh Battery", "144Hz Display"],
    specs: {
      Display: "6.78-inch AMOLED, 144Hz",
      Processor: "Snapdragon 8s Gen 3",
      RAM: "8GB",
      Storage: "128GB",
      Camera: "50MP + 2MP | 16MP Front",
      Battery: "6000mAh, 80W Fast Charging",
      OS: "Funtouch OS 14",
    },
    ramGb: 8,
    storageGb: 128,
    trending: true,
  }),
  toProduct({
    id: "m-3",
    name: "Nothing Phone (2a)",
    brand: "Nothing",
    category: "Mobiles",
    releaseYear: 2024,
    price: 22999,
    originalPrice: 27999,
    rating: 4.5,
    ratingCount: 10244,
    image:
      "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "256GB Storage", "5000mAh", "Glyph Interface"],
    specs: {
      Display: "6.7-inch AMOLED, 120Hz",
      Processor: "MediaTek Dimensity 7200 Pro",
      RAM: "8GB",
      Storage: "256GB",
      Camera: "50MP + 50MP | 32MP Front",
      Battery: "5000mAh, 45W Fast Charging",
      OS: "Nothing OS 2.5",
    },
    ramGb: 8,
    storageGb: 256,
  }),
  toProduct({
    id: "m-4",
    name: "OnePlus Nord 4",
    brand: "OnePlus",
    category: "Mobiles",
    releaseYear: 2024,
    price: 29999,
    originalPrice: 32999,
    rating: 4.5,
    ratingCount: 6430,
    image:
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "256GB Storage", "5500mAh Battery", "100W Charging"],
    specs: {
      Display: "6.74-inch AMOLED, 120Hz",
      Processor: "Snapdragon 7+ Gen 3",
      RAM: "8GB",
      Storage: "256GB",
      Camera: "50MP Sony LYT-600 + 8MP | 16MP Front",
      Battery: "5500mAh, 100W SUPERVOOC",
      OS: "OxygenOS 14",
    },
    ramGb: 8,
    storageGb: 256,
    bestChoice: true,
    trending: true,
  }),
  toProduct({
    id: "m-5",
    name: "Samsung Galaxy S24 FE",
    brand: "Samsung",
    category: "Mobiles",
    releaseYear: 2025,
    price: 44999,
    originalPrice: 54999,
    rating: 4.6,
    ratingCount: 3280,
    image:
      "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "256GB Storage", "Galaxy AI", "50MP Camera"],
    specs: {
      Display: "6.7-inch Dynamic AMOLED 2X, 120Hz",
      Processor: "Exynos 2400e",
      RAM: "8GB",
      Storage: "256GB",
      Camera: "50MP + 12MP + 8MP | 10MP Front",
      Battery: "4700mAh, 25W Fast Charging",
      OS: "Android 15, One UI 7",
    },
    ramGb: 8,
    storageGb: 256,
    trending: true,
  }),
  toProduct({
    id: "m-6",
    name: "Xiaomi 14 Civi",
    brand: "Xiaomi",
    category: "Mobiles",
    releaseYear: 2024,
    price: 38999,
    originalPrice: 42999,
    rating: 4.4,
    ratingCount: 2840,
    image:
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["12GB RAM", "512GB Storage", "Leica Cameras", "67W Charging"],
    specs: {
      Display: "6.55-inch AMOLED, 120Hz",
      Processor: "Snapdragon 8s Gen 3",
      RAM: "12GB",
      Storage: "512GB",
      Camera: "50MP + 50MP + 12MP | Dual 32MP Front",
      Battery: "4700mAh, 67W TurboCharge",
      OS: "Xiaomi HyperOS",
    },
    ramGb: 12,
    storageGb: 512,
  }),
  toProduct({
    id: "m-7",
    name: "Apple iPhone 16",
    brand: "Apple",
    category: "Mobiles",
    releaseYear: 2025,
    price: 79900,
    originalPrice: 84900,
    rating: 4.7,
    ratingCount: 4120,
    image:
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "128GB Storage", "A18 Chip", "48MP Fusion Camera"],
    specs: {
      Display: "6.1-inch Super Retina XDR",
      Processor: "Apple A18",
      RAM: "8GB",
      Storage: "128GB",
      Camera: "48MP Fusion + 12MP Ultra Wide | 12MP Front",
      Battery: "All-day battery life",
      OS: "iOS 18",
    },
    ramGb: 8,
    storageGb: 128,
    trending: true,
  }),
  toProduct({
    id: "m-8",
    name: "Realme GT 6",
    brand: "Realme",
    category: "Mobiles",
    releaseYear: 2024,
    price: 35999,
    originalPrice: 41999,
    rating: 4.4,
    ratingCount: 2210,
    image:
      "https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["12GB RAM", "256GB Storage", "5500mAh Battery", "Snapdragon 8s Gen 3"],
    specs: {
      Display: "6.78-inch LTPO AMOLED, 120Hz",
      Processor: "Snapdragon 8s Gen 3",
      RAM: "12GB",
      Storage: "256GB",
      Camera: "50MP Sony LYT-808 + 8MP | 32MP Front",
      Battery: "5500mAh, 120W SUPERVOOC",
      OS: "realme UI 5.0",
    },
    ramGb: 12,
    storageGb: 256,
  }),
  toProduct({
    id: "l-1",
    name: "ASUS Vivobook S 16 OLED",
    brand: "ASUS",
    category: "Laptops",
    releaseYear: 2024,
    price: 58990,
    originalPrice: 71990,
    rating: 4.2,
    ratingCount: 2310,
    image:
      "https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Ryzen 7", "16GB RAM", "512GB SSD", "3.2K OLED"],
    specs: {
      Display: "16-inch 3.2K OLED, 120Hz",
      Processor: "AMD Ryzen 7 8845HS",
      RAM: "16GB LPDDR5X",
      Storage: "512GB NVMe SSD",
      Graphics: "Radeon 780M",
      Battery: "75Wh",
      OS: "Windows 11 Home",
    },
    ramGb: 16,
    storageGb: 512,
    bestChoice: true,
    trending: true,
  }),
  toProduct({
    id: "l-2",
    name: "HP Pavilion 15",
    brand: "HP",
    category: "Laptops",
    releaseYear: 2024,
    price: 64990,
    originalPrice: 79990,
    rating: 4.1,
    ratingCount: 1890,
    image:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Intel Core i5", "16GB RAM", "1TB SSD", "15.6-inch"],
    specs: {
      Display: "15.6-inch FHD IPS",
      Processor: "Intel Core i5-13420H",
      RAM: "16GB DDR4",
      Storage: "1TB NVMe SSD",
      Graphics: "Intel UHD",
      Battery: "41Wh",
      OS: "Windows 11 Home",
    },
    ramGb: 16,
    storageGb: 1024,
  }),
  toProduct({
    id: "l-3",
    name: "Lenovo LOQ Gaming",
    brand: "Lenovo",
    category: "Laptops",
    releaseYear: 2024,
    price: 74990,
    originalPrice: 89990,
    rating: 4.6,
    ratingCount: 3124,
    image:
      "https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Ryzen 7", "16GB RAM", "512GB SSD", "RTX 4050"],
    specs: {
      Display: "15.6-inch FHD, 144Hz",
      Processor: "AMD Ryzen 7 7840HS",
      RAM: "16GB DDR5",
      Storage: "512GB NVMe SSD",
      Graphics: "NVIDIA RTX 4050 6GB",
      Battery: "60Wh",
      OS: "Windows 11 Home",
    },
    ramGb: 16,
    storageGb: 512,
    trending: true,
  }),
  toProduct({
    id: "l-4",
    name: "Apple MacBook Air M3",
    brand: "Apple",
    category: "Laptops",
    releaseYear: 2024,
    price: 104900,
    originalPrice: 114900,
    rating: 4.8,
    ratingCount: 3820,
    image:
      "https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["M3 Chip", "16GB RAM", "512GB SSD", "13.6-inch"],
    specs: {
      Display: "13.6-inch Liquid Retina",
      Processor: "Apple M3",
      RAM: "16GB Unified Memory",
      Storage: "512GB SSD",
      Graphics: "10-core GPU",
      Battery: "Up to 18 hours",
      OS: "macOS Sequoia",
    },
    ramGb: 16,
    storageGb: 512,
    bestChoice: true,
    trending: true,
  }),
  toProduct({
    id: "l-5",
    name: "Acer Swift Go 14",
    brand: "Acer",
    category: "Laptops",
    releaseYear: 2024,
    price: 67990,
    originalPrice: 76990,
    rating: 4.3,
    ratingCount: 1540,
    image:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Core Ultra 5", "16GB RAM", "512GB SSD", "OLED"],
    specs: {
      Display: "14-inch 2.8K OLED",
      Processor: "Intel Core Ultra 5 125H",
      RAM: "16GB LPDDR5X",
      Storage: "512GB NVMe SSD",
      Graphics: "Intel Arc Graphics",
      Battery: "65Wh",
      OS: "Windows 11 Home",
    },
    ramGb: 16,
    storageGb: 512,
  }),
  toProduct({
    id: "l-6",
    name: "Dell XPS 14",
    brand: "Dell",
    category: "Laptops",
    releaseYear: 2024,
    price: 149990,
    originalPrice: 164990,
    rating: 4.5,
    ratingCount: 980,
    image:
      "https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Core Ultra 7", "16GB RAM", "1TB SSD", "RTX 4050"],
    specs: {
      Display: "14.5-inch 3.2K OLED",
      Processor: "Intel Core Ultra 7 155H",
      RAM: "16GB LPDDR5X",
      Storage: "1TB NVMe SSD",
      Graphics: "NVIDIA RTX 4050",
      Battery: "69.5Wh",
      OS: "Windows 11 Home",
    },
    ramGb: 16,
    storageGb: 1024,
  }),
  toProduct({
    id: "l-7",
    name: "HP Omen Transcend 14",
    brand: "HP",
    category: "Laptops",
    releaseYear: 2024,
    price: 129990,
    originalPrice: 139990,
    rating: 4.4,
    ratingCount: 860,
    image:
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Core Ultra 7", "16GB RAM", "1TB SSD", "RTX 4060"],
    specs: {
      Display: "14-inch 2.8K OLED, 120Hz",
      Processor: "Intel Core Ultra 7 155H",
      RAM: "16GB LPDDR5X",
      Storage: "1TB NVMe SSD",
      Graphics: "NVIDIA RTX 4060",
      Battery: "71Wh",
      OS: "Windows 11 Home",
    },
    ramGb: 16,
    storageGb: 1024,
  }),
  toProduct({
    id: "t-1",
    name: "Xiaomi Pad 7",
    brand: "Xiaomi",
    category: "Tablets",
    releaseYear: 2025,
    price: 27999,
    originalPrice: 32999,
    rating: 4.4,
    ratingCount: 1480,
    image:
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "256GB Storage", "11.2-inch 144Hz", "8840mAh"],
    specs: {
      Display: "11.2-inch 3.2K, 144Hz",
      Processor: "Snapdragon 7+ Gen 3",
      RAM: "8GB",
      Storage: "256GB",
      Audio: "Quad speakers, Dolby Atmos",
      Battery: "8840mAh, 45W",
      OS: "Xiaomi HyperOS",
    },
    ramGb: 8,
    storageGb: 256,
    bestChoice: true,
  }),
  toProduct({
    id: "t-2",
    name: "Samsung Galaxy Tab S9 FE",
    brand: "Samsung",
    category: "Tablets",
    releaseYear: 2024,
    price: 36999,
    originalPrice: 44999,
    rating: 4.5,
    ratingCount: 2670,
    image:
      "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "128GB Storage", "IP68", "S Pen Included"],
    specs: {
      Display: "10.9-inch WQXGA, 90Hz",
      Processor: "Exynos 1380",
      RAM: "8GB",
      Storage: "128GB",
      Audio: "Dual speakers, AKG",
      Battery: "8000mAh, 45W",
      OS: "Android 14",
    },
    ramGb: 8,
    storageGb: 128,
    trending: true,
  }),
  toProduct({
    id: "t-3",
    name: "Apple iPad Air 11 M2",
    brand: "Apple",
    category: "Tablets",
    releaseYear: 2024,
    price: 59900,
    originalPrice: 64900,
    rating: 4.7,
    ratingCount: 5544,
    image:
      "https://images.unsplash.com/photo-1589739900243-4b52cd9ddf5d?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "128GB Storage", "11-inch", "M2 Chip"],
    specs: {
      Display: "11-inch Liquid Retina",
      Processor: "Apple M2",
      RAM: "8GB",
      Storage: "128GB",
      Camera: "12MP Rear | 12MP Front",
      Battery: "Up to 10 hours",
      OS: "iPadOS 18",
    },
    ramGb: 8,
    storageGb: 128,
    bestChoice: true,
  }),
  toProduct({
    id: "t-4",
    name: "Lenovo Tab Plus",
    brand: "Lenovo",
    category: "Tablets",
    releaseYear: 2024,
    price: 22999,
    originalPrice: 26999,
    rating: 4.2,
    ratingCount: 970,
    image:
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "128GB Storage", "11.5-inch", "JBL Speakers"],
    specs: {
      Display: "11.5-inch 2K, 90Hz",
      Processor: "Helio G99",
      RAM: "8GB",
      Storage: "128GB",
      Audio: "8 JBL Speakers",
      Battery: "8600mAh, 45W",
      OS: "Android 14",
    },
    ramGb: 8,
    storageGb: 128,
  }),
  toProduct({
    id: "t-5",
    name: "OnePlus Pad 2",
    brand: "OnePlus",
    category: "Tablets",
    releaseYear: 2024,
    price: 39999,
    originalPrice: 42999,
    rating: 4.5,
    ratingCount: 1260,
    image:
      "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["12GB RAM", "256GB Storage", "3K Display", "Snapdragon 8 Gen 3"],
    specs: {
      Display: "12.1-inch 3K, 144Hz",
      Processor: "Snapdragon 8 Gen 3",
      RAM: "12GB",
      Storage: "256GB",
      Audio: "Six speakers, Hi-Res Audio",
      Battery: "9510mAh, 67W",
      OS: "OxygenOS 14.1",
    },
    ramGb: 12,
    storageGb: 256,
    trending: true,
  }),
  toProduct({
    id: "t-6",
    name: "Apple iPad mini 7",
    brand: "Apple",
    category: "Tablets",
    releaseYear: 2025,
    price: 49900,
    originalPrice: 53900,
    rating: 4.6,
    ratingCount: 1180,
    image:
      "https://images.unsplash.com/photo-1589739900243-4b52cd9ddf5d?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["8GB RAM", "128GB Storage", "8.3-inch", "A17 Pro"],
    specs: {
      Display: "8.3-inch Liquid Retina",
      Processor: "Apple A17 Pro",
      RAM: "8GB",
      Storage: "128GB",
      Camera: "12MP Rear | 12MP Front",
      Battery: "Up to 10 hours",
      OS: "iPadOS 18",
    },
    ramGb: 8,
    storageGb: 128,
  }),
  toProduct({
    id: "s-1",
    name: "Samsung Galaxy Watch 7",
    brand: "Samsung",
    category: "Smartwatches",
    releaseYear: 2024,
    price: 27999,
    originalPrice: 32999,
    rating: 4.3,
    ratingCount: 1180,
    image:
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Wear OS", "BioActive Sensor", "GPS", "40mm"],
    specs: {
      Display: "1.3-inch Super AMOLED",
      Processor: "Exynos W1000",
      RAM: "2GB",
      Storage: "32GB",
      Sensors: "Heart Rate, ECG, SpO2",
      Battery: "300mAh",
      OS: "Wear OS powered by Samsung",
    },
    ramGb: 2,
    storageGb: 32,
    trending: true,
  }),
  toProduct({
    id: "s-2",
    name: "OnePlus Watch 3",
    brand: "OnePlus",
    category: "Smartwatches",
    releaseYear: 2025,
    price: 19999,
    originalPrice: 24999,
    rating: 4.2,
    ratingCount: 920,
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Dual Engine", "GPS", "100h Battery", "46mm"],
    specs: {
      Display: "1.43-inch AMOLED",
      Processor: "Snapdragon W5 + BES2700",
      RAM: "2GB",
      Storage: "32GB",
      Sensors: "Heart Rate, SpO2, Stress",
      Battery: "631mAh",
      OS: "Wear OS 4",
    },
    ramGb: 2,
    storageGb: 32,
    bestChoice: true,
  }),
  toProduct({
    id: "s-3",
    name: "Amazfit Balance",
    brand: "Amazfit",
    category: "Smartwatches",
    releaseYear: 2024,
    price: 15999,
    originalPrice: 19999,
    rating: 4.1,
    ratingCount: 680,
    image:
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Zepp OS", "GPS", "14-day Battery", "46mm"],
    specs: {
      Display: "1.5-inch AMOLED",
      Processor: "Dual-core chipset",
      RAM: "1GB",
      Storage: "8GB",
      Sensors: "BioTracker, SpO2, Sleep",
      Battery: "475mAh",
      OS: "Zepp OS",
    },
    ramGb: 1,
    storageGb: 8,
  }),
  toProduct({
    id: "e-1",
    name: "Sony WF-C700N",
    brand: "Sony",
    category: "Earbuds",
    releaseYear: 2024,
    price: 8990,
    originalPrice: 11990,
    rating: 4.4,
    ratingCount: 2120,
    image:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["ANC", "Bluetooth 5.2", "20h Battery", "IPX4"],
    specs: {
      Driver: "5mm",
      Battery: "Up to 20 hours with case",
      Audio: "DSEE, ANC",
      Connectivity: "Bluetooth 5.2",
      WaterResistance: "IPX4",
      Warranty: "1 Year",
    },
    ramGb: 1,
    storageGb: 8,
    trending: true,
  }),
  toProduct({
    id: "e-2",
    name: "JBL Live Pro 2",
    brand: "JBL",
    category: "Earbuds",
    releaseYear: 2024,
    price: 9999,
    originalPrice: 12999,
    rating: 4.3,
    ratingCount: 1650,
    image:
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["True ANC", "40h Battery", "6 Mics", "IPX5"],
    specs: {
      Driver: "11mm",
      Battery: "Up to 40 hours with case",
      Audio: "JBL Signature Sound",
      Connectivity: "Bluetooth 5.2",
      WaterResistance: "IPX5",
      Warranty: "1 Year",
    },
    ramGb: 1,
    storageGb: 8,
  }),
  toProduct({
    id: "e-3",
    name: "boAt Nirvana Ion",
    brand: "boAt",
    category: "Earbuds",
    releaseYear: 2024,
    price: 1999,
    originalPrice: 2999,
    rating: 4.2,
    ratingCount: 9580,
    image:
      "https://images.unsplash.com/photo-1605464315542-bda3e2f4e605?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["120h Battery", "ENx Tech", "Low Latency", "ASAP Charge"],
    specs: {
      Driver: "10mm",
      Battery: "Up to 120 hours with case",
      Audio: "boAt Signature",
      Connectivity: "Bluetooth 5.3",
      WaterResistance: "IPX4",
      Warranty: "1 Year",
    },
    ramGb: 1,
    storageGb: 8,
    bestChoice: true,
  }),
  toProduct({
    id: "e-4",
    name: "OnePlus Buds Pro 3",
    brand: "OnePlus",
    category: "Earbuds",
    releaseYear: 2025,
    price: 11999,
    originalPrice: 13999,
    rating: 4.5,
    ratingCount: 1820,
    image:
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Adaptive ANC", "44h Battery", "Dual Drivers", "LHDC"],
    specs: {
      Driver: "11mm woofer + 6mm tweeter",
      Battery: "Up to 44 hours with case",
      Audio: "LHDC 5.0, Dynaudio tuning",
      Connectivity: "Bluetooth 5.4",
      WaterResistance: "IP55",
      Warranty: "1 Year",
    },
    ramGb: 1,
    storageGb: 8,
    trending: true,
  }),
  toProduct({
    id: "e-5",
    name: "Samsung Galaxy Buds3 Pro",
    brand: "Samsung",
    category: "Earbuds",
    releaseYear: 2025,
    price: 15999,
    originalPrice: 19999,
    rating: 4.4,
    ratingCount: 1420,
    image:
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Adaptive ANC", "24-bit Audio", "Blade Design", "IP57"],
    specs: {
      Driver: "2-way speaker",
      Battery: "Up to 30 hours with case",
      Audio: "24-bit Hi-Fi audio",
      Connectivity: "Bluetooth 5.4",
      WaterResistance: "IP57",
      Warranty: "1 Year",
    },
    ramGb: 1,
    storageGb: 8,
  }),
  toProduct({
    id: "e-6",
    name: "Nothing Ear (2024)",
    brand: "Nothing",
    category: "Earbuds",
    releaseYear: 2024,
    price: 10999,
    originalPrice: 12999,
    rating: 4.3,
    ratingCount: 1560,
    image:
      "https://images.unsplash.com/photo-1605464315542-bda3e2f4e605?auto=format&fit=crop&w=900&q=80",
    shortSpecs: ["Smart ANC", "40.5h Battery", "LDAC", "ChatGPT Integration"],
    specs: {
      Driver: "11mm ceramic driver",
      Battery: "Up to 40.5 hours with case",
      Audio: "LDAC, Hi-Res Audio",
      Connectivity: "Bluetooth 5.3",
      WaterResistance: "IP54",
      Warranty: "1 Year",
    },
    ramGb: 1,
    storageGb: 8,
  }),
];
